# Generated by Django 3.1.7 on 2021-04-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_hoadonnhaphang_hoadontonhang_hoadonxuathang_nhaphang_tonhang'),
    ]

    operations = [
    ]
