# Generated by Django 3.2 on 2021-04-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20210418_0207'),
        ('finance', '0005_hoadonchuoikham_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoadonxuathang',
            options={'verbose_name': 'Hóa Đơn Xuất Hàng'},
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='hoa_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don_nhap_hang', to='finance.hoadonnhaphang'),
        ),
        migrations.AlterField(
            model_name='nhaphang',
            name='thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhap_hang_thuoc', to='medicine.thuoc'),
        ),
    ]
