# Generated by Django 3.1.7 on 2021-04-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='bac_si_chuyen_khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ketquachuyenkhoa',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
