# Generated by Django 3.1.7 on 2021-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_ketquatongquat_thoi_gian_tao'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongchucnang',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
