# Generated by Django 3.1.7 on 2021-04-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_phongchucnang_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlketqua',
            name='ket_qua_tong_quat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_ket_qua_tong_quat', to='clinic.ketquatongquat'),
        ),
    ]
