# Generated by Django 3.1.7 on 2021-04-05 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_htmlketqua_ket_qua_tong_quat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacsi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bac_si', to=settings.AUTH_USER_MODEL),
        ),
    ]
