# Generated by Django 3.1.7 on 2021-04-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20210406_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mauphieu',
            options={'permissions': (('can_add_analysis_note', 'Thêm mẫu phiếu'), ('can_change_analysis_note', 'Thay đổi mẫu phiếu'), ('can_view_analysis_note', 'Xem mẫu phiếu'), ('can_delete_analysis_note', 'Xóa mẫu phiếu')), 'verbose_name': 'Mẫu Phiếu', 'verbose_name_plural': 'Mẫu Phiếu'},
        ),
    ]
