# Generated by Django 3.2 on 2021-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20210407_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauphieu',
            name='codename',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
