# Generated by Django 3.1.7 on 2021-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20210329_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='ngay_gio_tao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày giờ tạo'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='thoi_gian_cap_nhat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
