# Generated by Django 3.1.7 on 2021-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20210329_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
