# Generated by Django 3.1.7 on 2021-03-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20210329_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
