# Generated by Django 3.1.7 on 2021-03-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20210329_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='ham_luong',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hàm lượng'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='nuoc_sx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='quyet_dinh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
