# Generated by Django 3.1.7 on 2021-03-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20210329_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia',
            field=models.CharField(max_length=255, null=True, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Đơn giá thành tiền'),
        ),
    ]
