# Generated by Django 3.1.7 on 2021-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210329_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='gia_bhyt',
            field=models.CharField(max_length=50, null=True, verbose_name='Giá bảo hiểm y tế'),
        ),
    ]
