# Generated by Django 3.1.7 on 2021-04-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_thuoc_gia_bhyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donthuoc',
            name='benh_nhan_vang_lai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
