# Generated by Django 3.1.7 on 2021-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_donthuoc_benh_nhan_vang_lai'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoclog',
            name='bao_hiem',
            field=models.BooleanField(default=True),
        ),
    ]
