# Generated by Django 3.1.7 on 2021-04-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_thuoclog_bao_hiem'),
    ]

    operations = [
    ]
