# Generated by Django 3.2 on 2021-04-16 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0010_mauphieu_codename'),
        ('medicine', '0014_auto_20210409_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donthuoc',
            name='bac_si_ke_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bac_si_ke_don', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='benh_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_thuoc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='chuoi_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_thuoc_chuoi_kham', to='clinic.chuoikham'),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.trangthaidonthuoc'),
        ),
    ]
