# Generated by Django 3.2 on 2021-04-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_auto_20210416_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomThuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True)),
                ('thoi_gian_cap_nhat', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm Thuốc',
                'verbose_name_plural': 'Nhóm Thuốc',
            },
        ),
        migrations.AddField(
            model_name='thuoc',
            name='nhom_thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_thuoc', to='medicine.nhomthuoc'),
        ),
    ]
