# Generated by Django 3.2 on 2021-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20210418_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia_tt',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Đơn giá thành tiền'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='gia_bhyt',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Giá bảo hiểm y tế'),
        ),
    ]
