# Generated by Django 3.2 on 2021-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_auto_20210422_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia',
            field=models.IntegerField(null=True, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia_tt',
            field=models.IntegerField(null=True, verbose_name='Đơn giá thành tiền'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='gia_bhyt',
            field=models.IntegerField(null=True, verbose_name='Giá bảo hiểm y tế'),
        ),
        migrations.RemoveField(
            model_name='thuoc',
            name='nhom_thuoc',
        ),
        migrations.AddField(
            model_name='thuoc',
            name='nhom_thuoc',
            field=models.ManyToManyField(related_name='nhom_thuoc', to='medicine.NhomThuoc'),
        ),
    ]
